management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: WelcomeAPI
    boot:
        admin:
            client:
                url: http://localhost:9090

